# Generated by Django 6.0.5 on 2026-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], default='breakfast', max_length=50),
        ),
    ]
